data:extend {
	{
		type = "string-setting",
		name = "rsbs-scan-missing-productivity",
		setting_type = "runtime-per-user",
		allowed_values = {
			"disable",
			"empty-slots",
			"non-productivity-slots",
			"not-best-available",
			"not-minimal-tier",
		},
		default_value = "non-productivity-slots",
		order = "a",
	},
	{
		type = "int-setting",
		name = "rsbs-scan-missing-productivity-tier",
		setting_type = "runtime-per-user",
		minimum_value = 1,
		default_value = 1,
		order = "a-a",
	},
	{
		type = "bool-setting",
		name = "rsbs-scan-missing-beacon-modules",
		setting_type = "runtime-per-user",
		default_value = true,
		order = "b",
	},
	{
		type = "bool-setting",
		name = "rsbs-scan-tick-crafting-limit",
		setting_type = "runtime-per-user",
		default_value = true,
		order = "c",
	},
	{
		type = "bool-setting",
		name = "rsbs-scan-backwards-belts",
		setting_type = "runtime-per-user",
		default_value = true,
		order = "d",
	},
	{
		type = "bool-setting",
		name = "rsbs-scan-belt-capacity", 
		setting_type = "runtime-per-user",
		default_value = true,
		order = "e",
	},
	{
		type = "bool-setting",
		name = "rsbs-scan-stray-loader-items",
		setting_type = "runtime-per-user",
		default_value = true,
		order = "f",
	},
	{
		type = "bool-setting",
		name = "rsbs-scan-logistic-chest-capacity",
		setting_type = "runtime-per-user",
		default_value = true,
		order = "g",
	},

	{
		type = "bool-setting",
		name = "rsbs-belt-capacity-splitters-only",
		setting_type = "runtime-per-user",
		default_value = false,
		order = "e-a",
	},
	{
		type = "bool-setting",
		name = "rsbs-belt-capacity-single-only",
		setting_type = "runtime-per-user",
		default_value = true,
		order = "e-b",
	},
	{
		type = "bool-setting",
		name = "rsbs-belt-capacity-strict-splitters",
		setting_type = "runtime-per-user",
		default_value = false,
		order = "e-c",
	},
}
