data:extend {
	{
		type = "bool-setting",
		name = "rsbs-scan-missing-productivity",
		setting_type = "runtime-per-user",
		default_value = true,
		order = "a",
	},
	{
		type = "bool-setting",
		name = "rsbs-scan-missing-beacon-modules",
		setting_type = "runtime-per-user",
		default_value = true,
		order = "b",
	},
	{
		type = "bool-setting",
		name = "rsbs-scan-tick-crafting-limit",
		setting_type = "runtime-per-user",
		default_value = true,
		order = "c",
	},
	{
		type = "bool-setting",
		name = "rsbs-scan-backwards-belts",
		setting_type = "runtime-per-user",
		default_value = true,
		order = "d",
	},
	{
		type = "bool-setting",
		name = "rsbs-scan-belt-capacity",
		setting_type = "runtime-per-user",
		default_value = true,
		order = "e",
	},
	{
		type = "bool-setting",
		name = "rsbs-scan-stray-loader-items",
		setting_type = "runtime-per-user",
		default_value = true,
		order = "f",
	},

	{
		type = "bool-setting",
		name = "rsbs-belt-capacity-splitters-only",
		setting_type = "runtime-per-user",
		default_value = false,
		order = "e-a",
	},
	{
		type = "bool-setting",
		name = "rsbs-belt-capacity-single-only",
		setting_type = "runtime-per-user",
		default_value = true,
		order = "e-b",
	},
	{
		type = "bool-setting",
		name = "rsbs-belt-capacity-strict-splitters",
		setting_type = "runtime-per-user",
		default_value = false,
		order = "e-c",
	},
}
